# Generated by Django 4.2 on 2023-07-25 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_transactions",
            name="delivery_completion_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 7, 25, 16, 5, 9, 765570)
            ),
        ),
        migrations.AddField(
            model_name="order_transactions",
            name="order_cancellation_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order_transactions",
            name="order_cancellation_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 7, 25, 16, 5, 9, 765582)
            ),
        ),
        migrations.AddField(
            model_name="order_transactions",
            name="provider_operator_code",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order_transactions",
            name="provision_completion_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="company_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 7, 25, 16, 5, 9, 765937)
            ),
        ),
        migrations.AlterField(
            model_name="operator_code_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 7, 25, 16, 5, 9, 768048)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 7, 25, 16, 5, 9, 765543)
            ),
        ),
        migrations.AlterField(
            model_name="page_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 7, 25, 16, 5, 9, 766594)
            ),
        ),
        migrations.AlterField(
            model_name="product_category_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 7, 25, 16, 5, 9, 766229)
            ),
        ),
        migrations.AlterField(
            model_name="product_info_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 7, 25, 16, 5, 9, 767409)
            ),
        ),
    ]
