# Generated by Django 4.2 on 2023-08-14 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 14, 7, 59, 10, 523303)
            ),
        ),
        migrations.AlterField(
            model_name="operator_code_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 14, 7, 59, 10, 525479)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="delivery_completion_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 14, 7, 59, 10, 522938)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_cancellation_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 14, 7, 59, 10, 522950)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 14, 7, 59, 10, 522913)
            ),
        ),
        migrations.AlterField(
            model_name="page_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 14, 7, 59, 10, 523961)
            ),
        ),
        migrations.AlterField(
            model_name="product_category_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 14, 7, 59, 10, 523599)
            ),
        ),
        migrations.AlterField(
            model_name="product_info_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 14, 7, 59, 10, 524771)
            ),
        ),
    ]
