# Generated by Django 4.1.1 on 2024-03-19 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_transactions',
            name='product_image_link_dest',
        ),
        migrations.RemoveField(
            model_name='product_info_master',
            name='product_image_link_dest',
        ),
        migrations.AddField(
            model_name='order_transactions',
            name='product_image',
            field=models.ImageField(default=1, upload_to='media/product_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_transactions',
            name='sequential_order_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_info_master',
            name='product_image',
            field=models.ImageField(default=1, upload_to='media/product_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 210135)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 209143)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 210024)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 208402)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 208410)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 208307)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='settlement_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 208422)),
        ),
        migrations.AlterField(
            model_name='ordertransactionitempdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 208774)),
        ),
        migrations.AlterField(
            model_name='ordertransactionpdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 208650)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 209368)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 209255)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 11, 56, 209698)),
        ),
    ]
