# Generated by Django 4.2 on 2023-12-13 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 840776)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 839717)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 840662)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 839521)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 839528)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 839398)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 839968)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 839847)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 2, 36, 26, 840310)),
        ),
    ]
