# Generated by Django 4.2 on 2024-02-08 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 635876)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 634851)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 635763)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 634185)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 634193)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 634056)),
        ),
        migrations.AlterField(
            model_name='ordertransactionitempdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 634482)),
        ),
        migrations.AlterField(
            model_name='ordertransactionpdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 634362)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 635085)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 634971)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 19, 42, 635422)),
        ),
    ]
