# Generated by Django 4.2 on 2024-02-08 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_admin_code_master_registration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 663330)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 662307)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 663216)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 661606)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 661613)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 661472)),
        ),
        migrations.AlterField(
            model_name='ordertransactionitempdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 661926)),
        ),
        migrations.AlterField(
            model_name='ordertransactionpdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 661799)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 662543)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 662428)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 2, 8, 7, 24, 17, 662874)),
        ),
    ]
