# Generated by Django 4.2 on 2023-08-10 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_order_transactions_delivery_completion_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator_code_master",
            name="operator_password",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 10, 18, 15, 24, 377679)
            ),
        ),
        migrations.AlterField(
            model_name="operator_code_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 10, 18, 15, 24, 381267)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="delivery_completion_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 10, 18, 15, 24, 376981)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_cancellation_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 10, 18, 15, 24, 377002)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 10, 18, 15, 24, 376951)
            ),
        ),
        migrations.AlterField(
            model_name="page_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 10, 18, 15, 24, 378805)
            ),
        ),
        migrations.AlterField(
            model_name="product_category_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 10, 18, 15, 24, 378338)
            ),
        ),
        migrations.AlterField(
            model_name="product_info_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 10, 18, 15, 24, 380159)
            ),
        ),
    ]
