# Generated by Django 4.1.1 on 2024-03-19 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_order_transactions_product_image_link_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 120450)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 119290)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 120332)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 118572)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 118580)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 118472)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='settlement_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 118592)),
        ),
        migrations.AlterField(
            model_name='ordertransactionitempdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 118952)),
        ),
        migrations.AlterField(
            model_name='ordertransactionpdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 118826)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 119614)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 119485)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 31, 13, 119980)),
        ),
    ]
