# Generated by Django 4.0.7 on 2023-12-15 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_admin_code_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 4, 41, 4, 681117)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 4, 41, 4, 682170)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 4, 41, 4, 681117)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 4, 41, 4, 681117)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 4, 41, 4, 681117)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 4, 41, 4, 681117)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 4, 41, 4, 681117)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 4, 41, 4, 682170)),
        ),
    ]
