# Generated by Django 4.2 on 2023-08-21 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_info_master_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 21, 18, 32, 32, 443590)
            ),
        ),
        migrations.AlterField(
            model_name="operator_code_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 21, 18, 32, 32, 448110)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="delivery_completion_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 21, 18, 32, 32, 442903)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_cancellation_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 21, 18, 32, 32, 442929)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 21, 18, 32, 32, 442853)
            ),
        ),
        migrations.AlterField(
            model_name="page_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 21, 18, 32, 32, 444674)
            ),
        ),
        migrations.AlterField(
            model_name="product_category_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 21, 18, 32, 32, 444222)
            ),
        ),
        migrations.AlterField(
            model_name="product_info_master",
            name="image",
            field=models.ImageField(default=None, upload_to="static/media"),
        ),
        migrations.AlterField(
            model_name="product_info_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2023, 8, 21, 18, 32, 32, 446033)
            ),
        ),
    ]
