# Generated by Django 4.1.1 on 2024-03-19 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_admin_code_master_registration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 181763)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 180729)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 181651)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 180030)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='lane_no',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 180038)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 179897)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='settlement_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 180051)),
        ),
        migrations.AlterField(
            model_name='ordertransactionitempdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 180397)),
        ),
        migrations.AlterField(
            model_name='ordertransactionpdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 180282)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 180996)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 180879)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 4, 51, 3, 181321)),
        ),
    ]
