# Generated by Django 4.0.7 on 2023-12-15 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_admin_code_master_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_code_master',
            old_name='operator_code',
            new_name='admin_code',
        ),
        migrations.RenameField(
            model_name='admin_code_master',
            old_name='operator_name',
            new_name='admin_name',
        ),
        migrations.RenameField(
            model_name='admin_code_master',
            old_name='operator_password',
            new_name='admin_password',
        ),
        migrations.AlterField(
            model_name='admin_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 15, 5, 15, 45, 750699)),
        ),
    ]
