# Generated by Django 4.1.1 on 2024-03-19 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_admin_code_master_registration_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 742839)),
        ),
        migrations.AlterField(
            model_name='company_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 741841)),
        ),
        migrations.AlterField(
            model_name='operator_code_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 742729)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='delivery_completion_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 741085)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_cancellation_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 741094)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='order_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 740977)),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='product_unit_price',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order_transactions',
            name='settlement_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 741107)),
        ),
        migrations.AlterField(
            model_name='ordertransactionitempdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 741464)),
        ),
        migrations.AlterField(
            model_name='ordertransactionpdf',
            name='transaction_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 741340)),
        ),
        migrations.AlterField(
            model_name='page_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 742068)),
        ),
        migrations.AlterField(
            model_name='product_category_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 741956)),
        ),
        migrations.AlterField(
            model_name='product_info_master',
            name='registration_time',
            field=models.TimeField(default=datetime.datetime(2024, 3, 19, 5, 44, 53, 742401)),
        ),
    ]
