# Generated by Django 4.2 on 2024-01-02 10:33

import core.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_admin_code_master_registration_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTransactionPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=core.models.get_pdf_url,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "transaction_time",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 1, 2, 10, 33, 1, 143242)
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="admin_code_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 145552)
            ),
        ),
        migrations.AlterField(
            model_name="company_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 143512)
            ),
        ),
        migrations.AlterField(
            model_name="operator_code_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 145311)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="delivery_completion_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 142880)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_cancellation_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 142890)
            ),
        ),
        migrations.AlterField(
            model_name="order_transactions",
            name="order_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 142859)
            ),
        ),
        migrations.AlterField(
            model_name="page_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 143984)
            ),
        ),
        migrations.AlterField(
            model_name="product_category_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 143752)
            ),
        ),
        migrations.AlterField(
            model_name="product_info_master",
            name="registration_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 1, 2, 10, 33, 1, 144632)
            ),
        ),
    ]
